# databases:
#   - name: django-project-boilerplate
#     databaseName: django-project-boilerplate
#     user: django-project-boilerplate

services:
  - type: web
    plan: free
    name: django-project-boilerplate
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn demo.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-project-boilerplate
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4